//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitBoostSiteGenerator.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BitBoostSiteGenerator.Localization.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Text_1001 {
            get {
                return ResourceManager.GetString("Text_1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Text_1002 {
            get {
                return ResourceManager.GetString("Text_1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Text_1003 {
            get {
                return ResourceManager.GetString("Text_1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Text_1004 {
            get {
                return ResourceManager.GetString("Text_1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Development Consulting.
        /// </summary>
        internal static string Text_1005 {
            get {
                return ResourceManager.GetString("Text_1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are looking for consultants that are experienced, easy going and spiced up with a strong focus on productivity, then you have come to the right place!.
        /// </summary>
        internal static string Text_1006 {
            get {
                return ResourceManager.GetString("Text_1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Out More.
        /// </summary>
        internal static string Text_1007 {
            get {
                return ResourceManager.GetString("Text_1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        internal static string Text_1008 {
            get {
                return ResourceManager.GetString("Text_1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!.
        /// </summary>
        internal static string Text_1009 {
            get {
                return ResourceManager.GetString("Text_1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can we help?.
        /// </summary>
        internal static string Text_1010 {
            get {
                return ResourceManager.GetString("Text_1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Text_1011 {
            get {
                return ResourceManager.GetString("Text_1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Get In Touch!.
        /// </summary>
        internal static string Text_1012 {
            get {
                return ResourceManager.GetString("Text_1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start your next project with us? That&apos;s great! Give us a call or send us an email and we will get back to you as soon as possible!.
        /// </summary>
        internal static string Text_1013 {
            get {
                return ResourceManager.GetString("Text_1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk To Us.
        /// </summary>
        internal static string Text_1014 {
            get {
                return ResourceManager.GetString("Text_1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture.
        /// </summary>
        internal static string Text_1015 {
            get {
                return ResourceManager.GetString("Text_1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration.
        /// </summary>
        internal static string Text_1016 {
            get {
                return ResourceManager.GetString("Text_1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tran.
        /// </summary>
        internal static string Text_1017 {
            get {
                return ResourceManager.GetString("Text_1017", resourceCulture);
            }
        }
    }
}
