// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BitBoostSiteGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class SinglePageApplicationTemplate : SinglePageApplicationTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<!DOCTYPE html>
<html lang=""en"">

  <head>

    <meta charset=""utf-8"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1, shrink-to-fit=no"">
    <meta name=""description"" content="""">
    <meta name=""author"" content="""">

    <title>");
            
            #line 16 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CompanyName));
            
            #line default
            #line hidden
            this.Write("</title>\r\n\r\n    <!-- Bootstrap core CSS -->\r\n    <link href=\"vendor/bootstrap/css" +
                    "/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n    <!-- Custom fonts for this template" +
                    " -->\r\n    <link href=\"vendor/font-awesome/css/font-awesome.min.css\" rel=\"stylesh" +
                    "eet\" type=\"text/css\">\r\n    <link href=\'https://fonts.googleapis.com/css?family=O" +
                    "pen+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800\' " +
                    "rel=\'stylesheet\' type=\'text/css\'>\r\n    <link href=\'https://fonts.googleapis.com/" +
                    "css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic\'" +
                    " rel=\'stylesheet\' type=\'text/css\'>\r\n\r\n    <!-- Plugin CSS -->\r\n    <link href=\"v" +
                    "endor/magnific-popup/magnific-popup.css\" rel=\"stylesheet\">\r\n\r\n    <!-- Custom st" +
                    "yles for this template -->\r\n    <link href=\"css/creative.min.css\" rel=\"styleshee" +
                    "t\">\r\n\r\n  </head>\r\n  <!--https://startbootstrap.com/template-overviews/creative/-" +
                    "->\r\n<!--https://www.pexels.com/search/development/-->\r\n<!--https://www.pexels.co" +
                    "m/photo/iphone-notebook-pen-working-34578/-->\r\n<!--https://css-tricks.com/design" +
                    "-considerations-text-images/-->\r\n  <body id=\"page-top\">\r\n\r\n    <!-- Navigation -" +
                    "->\r\n    <nav class=\"navbar navbar-expand-lg navbar-light fixed-top\" id=\"mainNav\"" +
                    ">\r\n      <div class=\"container\">\r\n        <a class=\"navbar-brand js-scroll-trigg" +
                    "er\" href=\"#page-top\"><img src=\"./img/logo.png\" /></a>\r\n        <button class=\"na" +
                    "vbar-toggler navbar-toggler-right\" type=\"button\" data-toggle=\"collapse\" data-tar" +
                    "get=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" a" +
                    "ria-label=\"Toggle navigation\">\r\n          <span class=\"navbar-toggler-icon\"></sp" +
                    "an>\r\n        </button>\r\n        <div class=\"collapse navbar-collapse\" id=\"navbar" +
                    "Responsive\">\r\n          <ul class=\"navbar-nav ml-auto\">\r\n            <li class=\"" +
                    "nav-item\">\r\n              <a class=\"nav-link js-scroll-trigger\" href=\"#page-top\"" +
                    ">");
            
            #line 49 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1001]));
            
            #line default
            #line hidden
            this.Write("</a>\r\n            </li>            \r\n            <li class=\"nav-item\">\r\n         " +
                    "     <a class=\"nav-link js-scroll-trigger\" href=\"#about\">");
            
            #line 52 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1002]));
            
            #line default
            #line hidden
            this.Write("</a>\r\n            </li>\r\n            <li class=\"nav-item\">\r\n              <a clas" +
                    "s=\"nav-link js-scroll-trigger\" href=\"#services\">");
            
            #line 55 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1003]));
            
            #line default
            #line hidden
            this.Write(@"</a>
            </li>
            <!--<li class=""nav-item"">
              <a class=""nav-link js-scroll-trigger"" href=""#portfolio"">Portfolio</a>
            </li>-->
            <li class=""nav-item"">
              <a class=""nav-link js-scroll-trigger"" href=""#contact"">");
            
            #line 61 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1004]));
            
            #line default
            #line hidden
            this.Write(@"</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <header class=""masthead text-center text-white d-flex"">
      <div class=""container my-auto"">
        <div class=""row"">
          <div class=""col-lg-10 mx-auto"">
            <h1 class=""text-uppercase"">
              <strong>");
            
            #line 73 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1005]));
            
            #line default
            #line hidden
            this.Write("</strong>\r\n            </h1>\r\n            <hr>\r\n          </div>\r\n          <div " +
                    "class=\"col-lg-8 mx-auto\">\r\n            <p class=\"text-faded mb-5\">");
            
            #line 78 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1006]));
            
            #line default
            #line hidden
            this.Write("</p>\r\n            <a class=\"btn btn-primary btn-xl js-scroll-trigger\" href=\"#abou" +
                    "t\">");
            
            #line 79 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1007]));
            
            #line default
            #line hidden
            this.Write(@"</a>
          </div>
        </div>
      </div>
    </header>

    <section class=""bg-primary"" id=""about"">
      <div class=""container"">
        <div class=""row"">
          <div class=""col-lg-8 mx-auto text-center"">
            <h2 class=""section-heading text-white"">");
            
            #line 89 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1008]));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n            <hr class=\"light my-4\">\r\n            <p class=\"text-faded mb-4" +
                    "\">");
            
            #line 91 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1009]));
            
            #line default
            #line hidden
            this.Write("</p>\r\n            <a class=\"btn btn-light btn-xl js-scroll-trigger\" href=\"#servic" +
                    "es\">");
            
            #line 92 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1010]));
            
            #line default
            #line hidden
            this.Write(@"</a>
          </div>
        </div>
      </div>
    </section>
      Arkitektur
      Integration
      Nyutveckling
      Förvaltning
      Agila processer
    <section id=""services"">
      <div class=""container"">
        <div class=""row"">
          <div class=""col-lg-12 text-center"">
            <h2 class=""section-heading"">");
            
            #line 106 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1011]));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n            <hr class=\"my-4\">\r\n          </div>\r\n        </div>\r\n      </d" +
                    "iv>\r\n      <div class=\"container\">\r\n        <div class=\"row\">\r\n          <div cl" +
                    "ass=\"col-lg-3 col-md-6 text-center\">\r\n            <div class=\"service-box mt-5 m" +
                    "x-auto\">\r\n              <i class=\"fa fa-4x fa-diamond text-primary mb-3 sr-icons" +
                    "\"></i>\r\n              <h3 class=\"mb-3\">Sturdy Templates</h3>\r\n              <p c" +
                    "lass=\"text-muted mb-0\">Our templates are updated regularly so they don\'t break.<" +
                    "/p>\r\n            </div>\r\n          </div>\r\n          <div class=\"col-lg-3 col-md" +
                    "-6 text-center\">\r\n            <div class=\"service-box mt-5 mx-auto\">\r\n          " +
                    "    <i class=\"fa fa-4x fa-paper-plane text-primary mb-3 sr-icons\"></i>\r\n        " +
                    "      <h3 class=\"mb-3\">Ready to Ship</h3>\r\n              <p class=\"text-muted mb" +
                    "-0\">You can use this theme as is, or you can make changes!</p>\r\n            </di" +
                    "v>\r\n          </div>\r\n          <div class=\"col-lg-3 col-md-6 text-center\">\r\n   " +
                    "         <div class=\"service-box mt-5 mx-auto\">\r\n              <i class=\"fa fa-4" +
                    "x fa-newspaper-o text-primary mb-3 sr-icons\"></i>\r\n              <h3 class=\"mb-3" +
                    "\">Up to Date</h3>\r\n              <p class=\"text-muted mb-0\">We update dependenci" +
                    "es to keep things fresh.</p>\r\n            </div>\r\n          </div>\r\n          <d" +
                    "iv class=\"col-lg-3 col-md-6 text-center\">\r\n            <div class=\"service-box m" +
                    "t-5 mx-auto\">\r\n              <i class=\"fa fa-4x fa-heart text-primary mb-3 sr-ic" +
                    "ons\"></i>\r\n              <h3 class=\"mb-3\">Made with Love</h3>\r\n              <p " +
                    "class=\"text-muted mb-0\">You have to make your websites with love these days!</p>" +
                    "\r\n            </div>\r\n          </div>\r\n        </div>\r\n        <div class=\"row\"" +
                    ">\r\n          <div class=\"col-lg-8 mx-auto text-center\">\r\n          <!--\r\n       " +
                    "     <h2 class=\"section-heading text-white\">");
            
            #line 145 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1008]));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n            <hr class=\"light my-4\">\r\n            <p class=\"text-faded mb-4" +
                    "\">");
            
            #line 147 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1009]));
            
            #line default
            #line hidden
            this.Write("</p>\r\n            -->\r\n            <a class=\"btn btn-primary btn-xl js-scroll-tri" +
                    "gger\" href=\"#contact\">");
            
            #line 149 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1014]));
            
            #line default
            #line hidden
            this.Write("</a>\r\n          </div>\r\n        </div>\r\n      </div>\r\n    </section>\r\n\r\n    <!--<" +
                    "section class=\"p-0\" id=\"portfolio\">\r\n      <div class=\"container-fluid p-0\">\r\n  " +
                    "      <div class=\"row no-gutters popup-gallery\">\r\n          <div class=\"col-lg-4" +
                    " col-sm-6\">\r\n            <a class=\"portfolio-box\" href=\"img/portfolio/fullsize/1" +
                    ".jpg\">\r\n              <img class=\"img-fluid\" src=\"img/portfolio/thumbnails/1.jpg" +
                    "\" alt=\"\">\r\n              <div class=\"portfolio-box-caption\">\r\n                <d" +
                    "iv class=\"portfolio-box-caption-content\">\r\n                  <div class=\"project" +
                    "-category text-faded\">\r\n                    Category\r\n                  </div>\r\n" +
                    "                  <div class=\"project-name\">\r\n                    Project Name\r\n" +
                    "                  </div>\r\n                </div>\r\n              </div>\r\n        " +
                    "    </a>\r\n          </div>\r\n          <div class=\"col-lg-4 col-sm-6\">\r\n         " +
                    "   <a class=\"portfolio-box\" href=\"img/portfolio/fullsize/2.jpg\">\r\n              " +
                    "<img class=\"img-fluid\" src=\"img/portfolio/thumbnails/2.jpg\" alt=\"\">\r\n           " +
                    "   <div class=\"portfolio-box-caption\">\r\n                <div class=\"portfolio-bo" +
                    "x-caption-content\">\r\n                  <div class=\"project-category text-faded\">" +
                    "\r\n                    Category\r\n                  </div>\r\n                  <div" +
                    " class=\"project-name\">\r\n                    Project Name\r\n                  </di" +
                    "v>\r\n                </div>\r\n              </div>\r\n            </a>\r\n          </" +
                    "div>\r\n          <div class=\"col-lg-4 col-sm-6\">\r\n            <a class=\"portfolio" +
                    "-box\" href=\"img/portfolio/fullsize/3.jpg\">\r\n              <img class=\"img-fluid\"" +
                    " src=\"img/portfolio/thumbnails/3.jpg\" alt=\"\">\r\n              <div class=\"portfol" +
                    "io-box-caption\">\r\n                <div class=\"portfolio-box-caption-content\">\r\n " +
                    "                 <div class=\"project-category text-faded\">\r\n                    " +
                    "Category\r\n                  </div>\r\n                  <div class=\"project-name\">" +
                    "\r\n                    Project Name\r\n                  </div>\r\n                </" +
                    "div>\r\n              </div>\r\n            </a>\r\n          </div>\r\n          <div c" +
                    "lass=\"col-lg-4 col-sm-6\">\r\n            <a class=\"portfolio-box\" href=\"img/portfo" +
                    "lio/fullsize/4.jpg\">\r\n              <img class=\"img-fluid\" src=\"img/portfolio/th" +
                    "umbnails/4.jpg\" alt=\"\">\r\n              <div class=\"portfolio-box-caption\">\r\n    " +
                    "            <div class=\"portfolio-box-caption-content\">\r\n                  <div " +
                    "class=\"project-category text-faded\">\r\n                    Category\r\n            " +
                    "      </div>\r\n                  <div class=\"project-name\">\r\n                    " +
                    "Project Name\r\n                  </div>\r\n                </div>\r\n              </" +
                    "div>\r\n            </a>\r\n          </div>\r\n          <div class=\"col-lg-4 col-sm-" +
                    "6\">\r\n            <a class=\"portfolio-box\" href=\"img/portfolio/fullsize/5.jpg\">\r\n" +
                    "              <img class=\"img-fluid\" src=\"img/portfolio/thumbnails/5.jpg\" alt=\"\"" +
                    ">\r\n              <div class=\"portfolio-box-caption\">\r\n                <div class" +
                    "=\"portfolio-box-caption-content\">\r\n                  <div class=\"project-categor" +
                    "y text-faded\">\r\n                    Category\r\n                  </div>\r\n        " +
                    "          <div class=\"project-name\">\r\n                    Project Name\r\n        " +
                    "          </div>\r\n                </div>\r\n              </div>\r\n            </a>" +
                    "\r\n          </div>\r\n          <div class=\"col-lg-4 col-sm-6\">\r\n            <a cl" +
                    "ass=\"portfolio-box\" href=\"img/portfolio/fullsize/6.jpg\">\r\n              <img cla" +
                    "ss=\"img-fluid\" src=\"img/portfolio/thumbnails/6.jpg\" alt=\"\">\r\n              <div " +
                    "class=\"portfolio-box-caption\">\r\n                <div class=\"portfolio-box-captio" +
                    "n-content\">\r\n                  <div class=\"project-category text-faded\">\r\n      " +
                    "              Category\r\n                  </div>\r\n                  <div class=\"" +
                    "project-name\">\r\n                    Project Name\r\n                  </div>\r\n    " +
                    "            </div>\r\n              </div>\r\n            </a>\r\n          </div>\r\n  " +
                    "      </div>\r\n      </div>\r\n    </section>\r\n\r\n    <section class=\"bg-dark text-w" +
                    "hite\">\r\n      <div class=\"container text-center\">\r\n        <h2 class=\"mb-4\">Free" +
                    " Download at Start Bootstrap!</h2>\r\n        <a class=\"btn btn-light btn-xl sr-bu" +
                    "tton\" href=\"http://startbootstrap.com/template-overviews/creative/\">Download Now" +
                    "!</a>\r\n      </div>\r\n    </section>\r\n    -->             \r\n\r\n    <section class=" +
                    "\"bg-primary\" id=\"contact\">\r\n      <div class=\"container\">\r\n        <div class=\"r" +
                    "ow\">\r\n          <div class=\"col-lg-8 mx-auto text-center\">\r\n            <h2 clas" +
                    "s=\"section-heading text-white\">");
            
            #line 264 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1012]));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n            <hr class=\"light my-4\">\r\n            <p class=\"text-faded mb-4" +
                    "\">");
            
            #line 266 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1013]));
            
            #line default
            #line hidden
            this.Write(@"</p>
          </div>
        </div>
        <div class=""row"">
          <!--<div class=""col-lg-4 ml-auto text-center"">
            <i class=""fa fa-phone fa-3x mb-3 sr-contact""></i>
            <p>123-456-6789</p>
          </div>-->
          <div class=""col-lg-4 mr-auto text-center"">
            <i class=""fa fa-envelope-o fa-3x mb-3 sr-contact""></i>
            <p text-faded mb-4>
              <a href=""mailto:");
            
            #line 277 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CompanyMail));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 277 "C:\FilesTemp\bitboostab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CompanyMail));
            
            #line default
            #line hidden
            this.Write(@"</a>
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Bootstrap core JavaScript -->
    <script src=""vendor/jquery/jquery.min.js""></script>
    <script src=""vendor/bootstrap/js/bootstrap.bundle.min.js""></script>

    <!-- Plugin JavaScript -->
    <script src=""vendor/jquery-easing/jquery.easing.min.js""></script>
    <script src=""vendor/scrollreveal/scrollreveal.min.js""></script>
    <script src=""vendor/magnific-popup/jquery.magnific-popup.min.js""></script>

    <!-- Custom scripts for this template -->
    <script src=""js/creative.min.js""></script>

  </body>

</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class SinglePageApplicationTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
