// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BitBoostSiteGenerator.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class SinglePageApplicationTemplate : SinglePageApplicationTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<!DOCTYPE html>
<html lang=""en"">

  <head>

    <meta charset=""utf-8"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1, shrink-to-fit=no"">
    <meta name=""description"" content="""">
    <meta name=""author"" content="""">

    <title>");
            
            #line 16 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CompanyName));
            
            #line default
            #line hidden
            this.Write("</title>\r\n\r\n    <!-- References -->\r\n    <!--https://startbootstrap.com/template-" +
                    "overviews/creative/-->\r\n    <!--https://www.pexels.com/search/development/-->\r\n " +
                    "   <!--https://www.pexels.com/photo/iphone-notebook-pen-working-34578/-->\r\n    <" +
                    "!--https://css-tricks.com/design-considerations-text-images/-->\r\n\r\n    <!-- Boot" +
                    "strap core CSS -->\r\n    <link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=" +
                    "\"stylesheet\">\r\n\r\n    <!-- Custom fonts for this template -->\r\n    <link href=\"ve" +
                    "ndor/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n " +
                    "   <link href=\'https://fonts.googleapis.com/css?family=Open+Sans:300italic,400it" +
                    "alic,600italic,700italic,800italic,400,300,600,700,800\' rel=\'stylesheet\' type=\'t" +
                    "ext/css\'>\r\n    <link href=\'https://fonts.googleapis.com/css?family=Merriweather:" +
                    "400,300,300italic,400italic,700,700italic,900,900italic\' rel=\'stylesheet\' type=\'" +
                    "text/css\'>\r\n\r\n    <!-- Plugin CSS -->\r\n    <link href=\"vendor/magnific-popup/mag" +
                    "nific-popup.css\" rel=\"stylesheet\">\r\n\r\n    <!-- Custom styles for this template -" +
                    "->\r\n    <link href=\"css/creative.css\" rel=\"stylesheet\">\r\n\r\n  </head>\r\n\r\n  <body " +
                    "id=\"page-top\">\r\n\r\n    <!-- Navigation -->\r\n    <nav class=\"navbar navbar-expand-" +
                    "lg navbar-dark fixed-top\" id=\"mainNav\">\r\n      <div class=\"container\">\r\n        " +
                    "<a class=\"navbar-brand js-scroll-trigger\" href=\"#page-top\"><img src=\"./img/logo." +
                    "png\" /></a>\r\n        <button class=\"navbar-toggler navbar-toggler-right\" type=\"b" +
                    "utton\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"nav" +
                    "barResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n          " +
                    "<span class=\"navbar-toggler-icon\"></span>\r\n        </button>\r\n        <div class" +
                    "=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n          <ul class=\"navbar-" +
                    "nav ml-auto\">\r\n            <li class=\"nav-item\">\r\n              <a class=\"nav-li" +
                    "nk js-scroll-trigger\" href=\"#page-top\">");
            
            #line 52 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1001]));
            
            #line default
            #line hidden
            this.Write("</a>\r\n            </li>            \r\n            <li class=\"nav-item\">\r\n         " +
                    "     <a class=\"nav-link js-scroll-trigger\" href=\"#about\">");
            
            #line 55 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1002]));
            
            #line default
            #line hidden
            this.Write("</a>\r\n            </li>\r\n            <li class=\"nav-item\">\r\n              <a clas" +
                    "s=\"nav-link js-scroll-trigger\" href=\"#services\">");
            
            #line 58 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1003]));
            
            #line default
            #line hidden
            this.Write(@"</a>
            </li>
            <!--<li class=""nav-item"">
              <a class=""nav-link js-scroll-trigger"" href=""#portfolio"">Portfolio</a>
            </li>-->
            <li class=""nav-item"">
              <a class=""nav-link js-scroll-trigger"" href=""#contact"">");
            
            #line 64 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1004]));
            
            #line default
            #line hidden
            this.Write(@"</a>
            </li>
            <li class=""nav-item"">
              <a class=""nav-link "" href=""index.sv-SE.html""><img src=""./img/lang_sv.png""></a>
            </li>
            <li class=""nav-item"">
                <a class=""nav-link "" href=""index.html""><img src=""./img/lang_uk.png""></a>
            </li>               
          </ul>
        </div>
      </div>
    </nav>

    <header class=""masthead text-center text-white d-flex"">
      <div class=""container my-auto"">
        <div class=""row"">
          <div class=""col-lg-10 mx-auto"">
            <h1 class=""text-uppercase"">
              <strong>");
            
            #line 82 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1005]));
            
            #line default
            #line hidden
            this.Write("</strong>\r\n            </h1>\r\n            <hr>\r\n          </div>\r\n          <div " +
                    "class=\"col-lg-8 mx-auto\">\r\n            <p class=\"text-white mb-5\">");
            
            #line 87 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1006]));
            
            #line default
            #line hidden
            this.Write("</p>\r\n            <a class=\"btn btn-primary btn-xl js-scroll-trigger\" href=\"#abou" +
                    "t\">");
            
            #line 88 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1007]));
            
            #line default
            #line hidden
            this.Write(@"</a>
          </div>
        </div>
      </div>
    </header>

    <section class=""bg-primary"" id=""about"">
      <div class=""container"">
        <div class=""row"">
          <div class=""col-lg-8 mx-auto text-center"">
            <h2 class=""section-heading "">");
            
            #line 98 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1002]));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n            <hr class=\"my-4\">\r\n            <p class=\"text-muted mb-4\">");
            
            #line 100 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1008]));
            
            #line default
            #line hidden
            this.Write("</p>               \r\n            <ul class=\"list-unstyled\">\r\n              <li><h" +
                    "5>");
            
            #line 102 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1009]));
            
            #line default
            #line hidden
            this.Write("<br/><small class=\"text-muted mb-4\">");
            
            #line 102 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1010]));
            
            #line default
            #line hidden
            this.Write("</small></h5></li>\r\n              <li><h5>");
            
            #line 103 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1011]));
            
            #line default
            #line hidden
            this.Write("<br/><small class=\"text-muted mb-1\">");
            
            #line 103 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1012]));
            
            #line default
            #line hidden
            this.Write("</small></h5></li>\r\n              <li><h5>");
            
            #line 104 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1013]));
            
            #line default
            #line hidden
            this.Write("<br/><small class=\"text-muted mb-1\">");
            
            #line 104 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1014]));
            
            #line default
            #line hidden
            this.Write("</small></h5></li>\r\n              <li><h5>");
            
            #line 105 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1015]));
            
            #line default
            #line hidden
            this.Write("<br/><small class=\"text-muted mb-1\">");
            
            #line 105 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1016]));
            
            #line default
            #line hidden
            this.Write("</small></h5></li>\r\n            </ul>\r\n            <p/>\r\n            <p class=\"te" +
                    "xt-muted mb-4\">");
            
            #line 108 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1017]));
            
            #line default
            #line hidden
            this.Write("</p>\r\n            <ul class=\"list-unstyled\">\r\n              <li><h5>");
            
            #line 110 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1018]));
            
            #line default
            #line hidden
            this.Write("</h5></li>\r\n              <li><h5>");
            
            #line 111 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1019]));
            
            #line default
            #line hidden
            this.Write("</h5></li>\r\n              <li><h5>");
            
            #line 112 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1020]));
            
            #line default
            #line hidden
            this.Write("</h5></li>\r\n              <li><h5>");
            
            #line 113 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1021]));
            
            #line default
            #line hidden
            this.Write("</h5></li>\r\n              <li><h5>");
            
            #line 114 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1022]));
            
            #line default
            #line hidden
            this.Write("</h5></li>\r\n              <li><h5>");
            
            #line 115 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1023]));
            
            #line default
            #line hidden
            this.Write("</h5></li>\r\n              <li><h5>");
            
            #line 116 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1024]));
            
            #line default
            #line hidden
            this.Write("</h5></li>\r\n            </ul>\r\n            </p>\r\n            <p class=\"text-muted" +
                    " mb-4\">");
            
            #line 119 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1025]));
            
            #line default
            #line hidden
            this.Write("</p> \r\n            <p class=\"text-white mb-5\"></p>\r\n            <a class=\"btn btn" +
                    "-primary btn-xl js-scroll-trigger\" href=\"#services\">");
            
            #line 121 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1026]));
            
            #line default
            #line hidden
            this.Write("</a>\r\n          </div>\r\n        </div>\r\n      </div>\r\n    </section>      \r\n    <" +
                    "section id=\"services\">\r\n      <div class=\"container\">\r\n        <div class=\"row\">" +
                    "\r\n          <div class=\"col-lg-12 text-center\">\r\n            <h2 class=\"section-" +
                    "heading\">");
            
            #line 130 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1003]));
            
            #line default
            #line hidden
            this.Write(@"</h2>
            <hr class=""my-4"">
          </div>
        </div>
      </div>
      <div class=""container"">
        <div class=""row"">
          <div class=""col-lg-4 col-md-6 text-center"">
              <div class=""service-box mt-5 mx-auto"">
                <i class=""fa fa-4x fa-keyboard-o text-primary mb-3 sr-icons""></i>
                <h3 class=""mb-3"">");
            
            #line 140 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1027]));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n                <p class=\"text-muted mb-0\">");
            
            #line 141 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1028]));
            
            #line default
            #line hidden
            this.Write(@"</p>
              </div>
            </div>    
          <div class=""col-lg-4 col-md-6 text-center"">
            <div class=""service-box mt-5 mx-auto"">
              <i class=""fa fa-4x fa-diamond text-primary mb-3 sr-icons""></i>
              <h3 class=""mb-3"">");
            
            #line 147 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1029]));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n              <p class=\"text-muted mb-0\">");
            
            #line 148 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1030]));
            
            #line default
            #line hidden
            this.Write(@"</p>
            </div>
          </div>
          <div class=""col-lg-4 col-md-6 text-center"">
            <div class=""service-box mt-5 mx-auto"">
              <i class=""fa fa-4x fa-handshake-o text-primary mb-3 sr-icons""></i>
              <h3 class=""mb-3"">");
            
            #line 154 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1031]));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n              <p class=\"text-muted mb-0\">");
            
            #line 155 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1032]));
            
            #line default
            #line hidden
            this.Write(@"</p>
            </div>
          </div>
          <div class=""col-lg-4 col-md-6 text-center"">
              <div class=""service-box mt-5 mx-auto"">
                <i class=""fa fa-4x fa-lightbulb-o text-primary mb-3 sr-icons""></i>
                <h3 class=""mb-3"">");
            
            #line 161 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1033]));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n                <p class=\"text-muted mb-0\">");
            
            #line 162 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1034]));
            
            #line default
            #line hidden
            this.Write(@"</p>
              </div>
            </div>    
          <div class=""col-lg-4 col-md-6 text-center"">
            <div class=""service-box mt-5 mx-auto"">
              <i class=""fa fa-4x fa-bug text-primary mb-3 sr-icons""></i>
              <h3 class=""mb-3"">");
            
            #line 168 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1035]));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n              <p class=\"text-muted mb-0\">");
            
            #line 169 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1036]));
            
            #line default
            #line hidden
            this.Write(@"</p>
            </div>
          </div>
          <div class=""col-lg-4 col-md-6 text-center"">
            <div class=""service-box mt-5 mx-auto"">
              <i class=""fa fa-4x fa-rocket text-primary mb-3 sr-icons""></i>
              <h3 class=""mb-3"">");
            
            #line 175 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1037]));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n              <p class=\"text-muted mb-0\">");
            
            #line 176 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1038]));
            
            #line default
            #line hidden
            this.Write(@"</p>
            </div>
          </div>
        </div>
        <div class=""row"">
          <div class=""col-lg-8 mx-auto text-center"">
            <p class=""text-white mb-5""></p>
            <a class=""btn btn-primary btn-xl js-scroll-trigger"" href=""#contact"">");
            
            #line 183 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1039]));
            
            #line default
            #line hidden
            this.Write(@"</a>
          </div>
        </div>
      </div>
    </section>      

    <section class=""bg-primary"" id=""contact"">      
      <div class=""container"">
        <div class=""row"">
          <div class=""col-lg-8 mx-auto text-center"">
            <h2 class=""section-heading"">");
            
            #line 193 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1040]));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n            <hr class=\"my-4\">\r\n            <p class=\"text-muted mb-4\">");
            
            #line 195 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1041]));
            
            #line default
            #line hidden
            this.Write("</p>\r\n            <p class=\"text-muted mb-4\">");
            
            #line 196 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1042]));
            
            #line default
            #line hidden
            this.Write(@"</p>
          </div>
        </div>
        <div class=""row"">
          <div class=""col-lg-1 col-md-0 mx-auto text-center""></div>         
          <div class=""col-lg-3 col-md-4 mx-auto text-center"">            
              <script type=""text/javascript"" src=""https://secure.skypeassets.com/i/scom/js/skype-uri.js""></script>                              
              <div style=""background:#F29918; margin:0rem 3rem; border: none;border-radius: 300px;"" id=""SkypeButton_Call_fredrik_2549_1"">
                <script type=""text/javascript"">
                Skype.ui({
                  ""name"": ""chat"",
                  ""element"": ""SkypeButton_Call_fredrik_2549_1"",
                  ""participants"": [""fredrik_2549""],
                  ""imageColor"": ""white"",
                  ""imageSize"": 32
                });
               </script>
              </div>
          </div> 
          <!-- 
          <div class=""col-lg-3 col-md-4 mx-auto text-center"">
            <i class=""fa fa-phone fa-3x mb-3 sr-contact text-primary""></i>
            <p class=""text-muted mb-4"">+46 123 45 67 89</p>
          </div> 
          -->
          <div class=""col-lg-3 col-md-4 mx-auto text-center"">
            <a href=""mailto:");
            
            #line 222 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CompanyMail));
            
            #line default
            #line hidden
            this.Write("\"><i class=\"fa fa-envelope-o fa-3x mb-3 sr-contact text-primary\"></i></a>\r\n      " +
                    "      <p class=\"text-muted mb-4\">\r\n              <a href=\"mailto:");
            
            #line 224 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CompanyMail));
            
            #line default
            #line hidden
            this.Write("\">");
            
            #line 224 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CompanyMail));
            
            #line default
            #line hidden
            this.Write(@"</a>
            </p>
          </div>
          <div class=""col-lg-1 col-md-0 mx-auto text-center""></div>         
        </div>
      </div>
    </section>

    <section class=""bg-footer section-footer"" id=""footer"">
        <div class=""container"">
          <div class=""row"">
            <div class=""col-lg-8 mx-auto text-center"">
              <p class=""mb-4"" />
              <p class=""mb-4 text-white""> ");
            
            #line 237 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CompanyName));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 237 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1043]));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 237 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(OrganizationNumber));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 237 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Localizer.Text[1044]));
            
            #line default
            #line hidden
            this.Write(" | ");
            
            #line 237 "C:\FilesTemp\devuroab.github.io\BitBoostSiteGenerator\BitBoostSiteGenerator\Templates\SinglePageApplicationTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(CompanyMail));
            
            #line default
            #line hidden
            this.Write(@"</p>
            </div>
          </div>
        </div>
    </section>
    <!-- Bootstrap core JavaScript -->
    <script src=""vendor/jquery/jquery.min.js""></script>
    <script src=""vendor/bootstrap/js/bootstrap.bundle.min.js""></script>

    <!-- Plugin JavaScript -->
    <script src=""vendor/jquery-easing/jquery.easing.min.js""></script>
    <script src=""vendor/scrollreveal/scrollreveal.min.js""></script>
    <script src=""vendor/magnific-popup/jquery.magnific-popup.min.js""></script>

    <!-- Custom scripts for this template -->
    <script src=""js/creative.min.js""></script>

  </body>

</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class SinglePageApplicationTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
